---
num_clients: 2 # total number of clients
num_classes: 2 # binary classification
num_features: 13 # total number of features
num_local_epochs: 1 # number of local epochs
num_rounds: 50
learning_rate: 0.01
penalty: .0001
momentum: 0.5
num_keep: 6
agg: fedht
iterht: False
data: ucihd

client_resources:
  num_cpus: 7
  num_gpus: 1

dataset:
  name: mnist
  split: sample
  num_classes: 10
  seed: 42
  num_clients: ${num_clients}
  fraction: 0.8

fit_config:
  drop_client: false
  epochs: ${num_local_epochs}
  batch_size: ${batch_size}
  learning_rate: ${learning_rate}
  weight_decay: ${weight_decay}

strategy:
  fraction_fit: 1.0
  fraction_evaluate: 1.0
  min_fit_clients: 2
  min_evaluate_clients: 2
  min_available_clients: 2
  evaluate_fn: null
  on_fit_config_fn: null
  on_evaluate_config_fn: null
